### ISSUE TITLE
原意为模组提供部分模型或贴图Provide some model or texture

### ISSUE THREAD

**Issue by Slimeli-32767** [RealAntEngineer/creating_space#13]
This mod is a good substitute to ad-astra in create modpackage! I would to provide some model or texture support for this mod, and I put some of my works in the end.

If you think that I can do it for this mod, please sent e-mail to 384362798@qq.com or contact me on https://space.bilibili.com/310622238

I really want to see create style rockets!

![textures](https://github.com/RealAntEngineer/creating_space/assets/164589261/cdb70997-ad71-46cc-bb30-dfc630ca93e4)
![model](https://github.com/RealAntEngineer/creating_space/assets/164589261/e8afd9e2-9f0a-4019-aa62-6bbe2016fdfe)

**Comment by Slimeli-32767** [comment]
Because it is difficult to get a stable network connection with github in China, it may take me several days to process the information on github.  I'm sorry if I don't reply in time.

**Comment by 22858** [comment]
如果有人回复你的话，github应该会发邮件给你

**Comment by RealAntEngineer** [comment]
@Slimeli-32767 You can provide textures and model to this mod. I have send an email some time ago I don't know if you have seen it.

**Comment by Slimeli-32767** [comment]
> 您可以为此模组提供纹理和模型。我前段时间发了一封电子邮件，不知道你有没有看过。

I just sent an email a few minutes ago. Please tell me if you don't receive it

**Comment by RealAntEngineer** [comment]
> > 您可以为此模组提供纹理和模型。我前段时间发了一封电子邮件，不知道你有没有看过。
> 
> I just sent an email a few minutes ago. Please tell me if you don't receive it

I havn't recived anything yet, where did you send it ?

**Comment by Slimeli-32767** [comment]
> > > 您可以为此模组提供纹理和模型。我前段时间发了一封电子邮件，不知道你有没有看过。
> > 
> > 
> > 几分钟前我刚刚发了一封电子邮件。如果您没有收到，请告诉我
> 
> 我还没有收到任何东西，你把它寄到哪里了？

Oh, It includes 39 textures and 2 models, but I accidentally sent it to notifications@github.com XD
By the way, my email 384362798@qq.com dosen't recive anything , maybe you can try this: slimeli@mail.dlut.edu.cn 
: )

**Comment by Slimeli-32767** [comment]
Or I just sent it to public, following CC-BY-SA4.0
[CarrierRocket&SolarPanel.zip](https://github.com/RealAntEngineer/creating_space/files/15425547/CarrierRocket.SolarPanel.zip)
[textures.zip](https://github.com/RealAntEngineer/creating_space/files/15425543/textures.zip)

**Comment by RealAntEngineer** [comment]
> Or I just sent it to public, following CC-BY-SA4.0 [CarrierRocket&SolarPanel.zip](https://github.com/RealAntEngineer/creating_space/files/15425547/CarrierRocket.SolarPanel.zip) [textures.zip](https://github.com/RealAntEngineer/creating_space/files/15425543/textures.zip)
I have send a new email to slimeli@mail.dlut.edu.cn. If you havn't recived it : can you remake some texture of my mod ?

**Comment by Slimeli-32767** [comment]
> > 或者我只是在CC-BY-SA4.0 [CarrierRocket&SolarPanel.zip](https://github.com/RealAntEngineer/creating_space/files/15425547/CarrierRocket.SolarPanel.zip)之后将其发送给公众[textures.zip](https://github.com/RealAntEngineer/creating_space/files/15425543/textures.zip)我已向 [slimeli@mail.dlut.edu.cn](mailto:slimeli@mail.dlut.edu.cn) 发送了一封新电子邮件。如果你还没有收到它：你能重新制作我的模组的一些纹理吗？

I got it and I have replied :)
